package com.github.kezhenxu94.playground.leetcode;

import java.util.HashMap;
import java.util.Map;

/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Solution389FindTheDifference {

    public char findTheDifference(String s, String t) {
        Map<Character, Integer> charCount = new HashMap<Character, Integer>();
        for (char c : s.toCharArray())
            charCount.put(c, charCount.getOrDefault(c, 0) + 1);
        for (char c : t.toCharArray())
            charCount.put(c, charCount.getOrDefault(c, 0) - 1);
        for (Map.Entry<Character, Integer> entry : charCount.entrySet())
            if (entry.getValue() != 0)
                return entry.getKey();
        return '\0';
    }

}
